### ISSUE TITLE
Failing with backstage 1.21.0  version

### ISSUE THREAD

**Issue by ichasco-heytrade** [arhill05/backstage-plugin-scaffolder-backend-module-slack#1]
The plugin is failing when upgrading backstage to v1.21.0 version

```
Backend failed to start up Error: Invalid configuration schema in node_modules/@mdude2314/backstage-plugin-scaffolder-backend-module-slack/node_modules/@backstage/backend-common/config.d.ts, the following definitions are not supported:

  Partial<{[key:string]:unknown;password:string;}>
    at /app/node_modules/@backstage/config-loader/dist/index.cjs.js:367:15
    at Array.map (<anonymous>)
    at compileTsSchemas (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:341:27)
    at async collectConfigSchemas (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:318:21)
    at async Object.loadConfigSchema (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:507:15)
    at async Object.createConfigSecretEnumerator (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:196:18)
    at async Object.loadBackendConfig (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:454:28)
    at async main (/app/packages/backend/dist/index.cjs.js:270:18)
```

```
yarn run v1.22.19
$ /app/node_modules/.bin/backstage-cli info
OS:   Linux 6.6.7-4-MANJARO - linux/x64
node: v18.19.0
yarn: 1.22.19
cli:  0.25.0 (installed)
backstage:  1.21.0

Dependencies:
  @backstage/app-defaults                          1.4.1
  @backstage/backend-app-api                       0.4.5
  @backstage/backend-common                        0.19.1
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.4
  @backstage/backend-tasks                         0.5.4
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.2
  @backstage/cli                                   0.22.9
  @backstage/config-loader                         1.3.2
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.0
  @backstage/core-components                       0.13.3
  @backstage/core-plugin-api                       1.5.3
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.15
  @backstage/integration                           1.5.1
  @backstage/plugin-api-docs                       0.9.6
  @backstage/plugin-app-backend                    0.3.47
  @backstage/plugin-auth-backend                   0.18.5
  @backstage/plugin-auth-node                      0.2.16
  @backstage/plugin-catalog-backend                1.11.0
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.32
  @backstage/plugin-catalog-import                 0.9.10
  @backstage/plugin-catalog-node                   1.4.0
  @backstage/plugin-catalog-react                  1.8.0
  @backstage/plugin-catalog                        1.12.0
  @backstage/plugin-events-node                    0.2.8
  @backstage/plugin-github-actions                 0.6.1
  @backstage/plugin-org                            0.6.10
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.10
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.2.41
  @backstage/plugin-scaffolder-backend             1.15.1
  @backstage/plugin-scaffolder-common              1.3.2
  @backstage/plugin-scaffolder-node                0.1.5
  @backstage/plugin-scaffolder-react               1.5.1
  @backstage/plugin-scaffolder                     1.14.1
  @backstage/plugin-search-backend-module-catalog  0.1.3
  @backstage/plugin-search-backend-module-pg       0.5.8
  @backstage/plugin-search-backend-module-techdocs 0.1.3
  @backstage/plugin-search-backend-node            1.2.3
  @backstage/plugin-search-backend                 1.3.3
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.3
  @backstage/plugin-search                         1.3.3
  @backstage/plugin-tech-radar                     0.6.6
  @backstage/plugin-techdocs-backend               1.6.4
  @backstage/plugin-techdocs-module-addons-contrib 1.0.15
  @backstage/plugin-techdocs-node                  1.7.3
  @backstage/plugin-techdocs-react                 1.1.8
  @backstage/plugin-techdocs                       1.6.5
  @backstage/plugin-user-settings                  0.7.5
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.1
  @backstage/theme                                 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
```

```
node@d989cd50c07c:/app$ yarn list --pattern slack
yarn list v1.22.19
warning workspace-aggregator-1b40484b-87ba-4236-8dd7-81a4ecaa2c34 > backend > @backstage/plugin-scaffolder-backend > @backstage/plugin-scaffolder-backend-module-gitlab > @gitbeaker/node@35.8.1: Please use its successor @gitbeaker/rest
└─ @mdude2314/backstage-plugin-scaffolder-backend-module-slack@1.0.2
```

**Comment by arhill05** [comment]
Hey @ichasco-heytrade! I'm looking at this this morning. Can you give me a little more info:

- What version of Backstage did you upgrade from?
- Are you using the [new backend system](https://backstage.io/docs/backend-system/building-plugins-and-modules/migrating) in Backstage?

**Comment by ichasco-heytrade** [comment]
Hi!

I upgraded from 1.19.0
Yes, I am using the new backend system.

Could you reproduce it?

Thanks

**Comment by arhill05** [comment]
@ichasco-heytrade this plugin has not been migrated to the new backend system yet. Can you make sure it is being imported and used with the instructions for legacy plugins in the new backend system migration guide? https://backstage.io/docs/backend-system/building-backends/migrating#migrating-the-index-file

**Comment by arhill05** [comment]
This plugin has been migrated to the new backend system as of version 3.0.0. Please try this again with the new backend system and see if your issue persists. If it does, feel free to open another :)
